### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by ynatividade** [NicholasEli/jGram#5]
Hi Nicolas,
Thanks for the jGram.
I would to know if is possible turn the background transparent? Because I wanna to use the module on my footer, that is black, and the white square background don't combine with the footer...
Thanks in advance!

**Comment by NicholasEli** [comment]
Hello, sorry I did not see this sooner. I can certainly create styles options for you to use. In the mean time I can help you adjust the styling manually if you would like to send me and email nicholasbydesign@gamil.com.

I thought no one was using this module, so I haven't been updating it regularly. Turns out I was wrong, I have gotten a lot a support requests this month. So let me know how I can help you, until I create the update.

**Comment by NicholasEli** [comment]
This options is now available, if you redownload the module. This update will contain the option for background color. Thanks for you input, please let me know if there is anything else I can approach.
